### ISSUE TITLE
Make scaling up and down more robust

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-kubernetes#123]
As a reminder, Dask users scale clusters using a Cluster API with the scale
method.

```python
cluster.scale(10)  # set the cluster to ten workers total
```

Currently in Dask-kubernetes we implement this API with the following two methods

```python
async def _scale_up(self, n: int):
    ...

async def _scale_down(self, workers: List[str])
    ...
```

However, our logic in these methods isn't foolproof, and we can get into some
bad situations if the user scales up and down rapidly without waiting for
thigns to settle.  This case happens somewhat frequently, especially when using
Dask's [adaptive scaling](http://docs.dask.org/en/latest/setup/adaptive.html) which calls scale based on the current activity
and perceived need in the scheduler.

There is some effort in `scale_up` and `scale_down` to be clever around:

-  Removing terminated pods
-  Removing pods that are Pending before removing actual workers
-  Accounting for Pending as well as Running pods when we scale up

However our current tests show that we're not very successful in ensuring that
we don't run into a bad situation.  In particular if you look through the test
suite for tests named `test_scale_*` that ar marked with `@pytest.mark.xfail`
you'll see some failures where combinations of calls of scaling up and down
result in a state where the user has asked for a certain number of workers and
we fail to deliver that to them.

Ideally calling `scale` would pin a target number of workers and we would
continuously endeavor to meet this target.  In principle Kubernetes could
handle this for us, but we want to have manual control over pods so that we can
scale them down mindfully of current results.  Dask already has functions to
determine which workers to kill given a target number, and move data off of
them, look for `select_workers_to_close` and `retire_workers`.

*Note: This became a more pressing issue when we switched to using async/await style code (I'm not sure why).  Near term work here should target the `dev` branch.*

**Comment by JoeJasinski** [comment]
Hi, I'm new to this project, so I don't know all of the ins and outs yet. If I understand correctly, pods are individually spawned and scaled based on the yaml template (or other means of specification). 

However, I was wondering if it would make sense to use a kubernetes Deployment instead of individual pods to scale up and down the cluster. If a deployment is used, then kubernetes itself can re-spawn pods that die instead of having to implement methods to manually do this housekeeping. 

I realize that there is probably a reason for this choice to use individual pods, but was just wondering if using deployments had been considered. Or maybe I'm misunderstanding how it works...

**Comment by jacobtomlinson** [comment]
Thanks for raising this @JoeJasinski. This comes up a lot. [Here's an answer I gave recently.](https://github.com/dask/dask-kubernetes/issues/168#issuecomment-517210364)

**Comment by jacobtomlinson** [comment]
Now that scaling logic is upstream in dask/distributed I'm going to close this.
