### ISSUE TITLE
Working with big data on Dask Kubernetes in Azure Kubernetes Service(AKS)

### ISSUE THREAD

**Issue by pintuiitbhi** [dask/dask-kubernetes#151]
> I want do analysis on a dataset(like csv file) of 8gb which is in my laptop hard disk. I have already setup a dask kubernetes cluster on AKS with 1 scheduler and 3 worker with 7 gb each.

**How can I work on my dataset using this dask kubernetes cluster on AKS?**

**Which file system to share dataset between worker will be best for this purpose?**

Any suggestion where I should store this dataset so that I can work on this dataset easily.

The method should work from both a jupyter notebook and from a python file also.

**Comment by TomAugspurger** [comment]
Probably s3

**Comment by pintuiitbhi** [comment]
I have already service of Azure. Is there any other option apart from "s3". I am already using Azure.

**Comment by mrocklin** [comment]
See http://docs.dask.org/en/latest/remote-data-services.html

cc @martindurant

**Comment by TomAugspurger** [comment]
Sorry I misread AKS as Amazon’s Kubernetes service.

**Comment by martindurant** [comment]
You will need to install https://github.com/dask/dask-adlfs and https://pypi.org/project/azure-datalake-store/ to gain the `"adl:"` protocol for azure datalake. This is mentioned at http://docs.dask.org/en/latest/remote-data-services.html#azure-datalake

Note that azure blob and azure storage version 2 are not supported, due to no one having spent the time to do so. Given my work on https://filesystem-spec.readthedocs.io/en/latest/ , and using https://github.com/azure/azurite as the test backend, the effort required would not be great.

**Comment by jakirkham** [comment]
@pintuiitbhi, have you had a chance to try any of the suggestions here?

**Comment by pintuiitbhi** [comment]
@jakirkham I will let you guys know, once I test it. Thank you all for helping me.

**Comment by TomAugspurger** [comment]
Closing, since this doesn't strictly seem to be a dask-kubernetes issue. Let us know if you have feedback on how things go.
