### ISSUE TITLE
dask-kubernetes is not able to connect to kubernetes cluster on azure kubernetes service(AKS)

### ISSUE THREAD

**Issue by pintuiitbhi** [dask/dask-kubernetes#152]
I have a kubernetes cluster on Azure Kubernetes Service.
How can I connect to workers on Kubernetes. In my dashboard, it shows no worker. When I try to run code , it just hangs because it is not able to find any worker. 

What setting should I do.

When I execute the command 
`kubectl get pods`
it gives No resources. While when I execute 
`kubectl get services`
It gives 
```
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.0.0.2     <none>        443/TCP   15h
```

**Comment by TomAugspurger** [comment]
Are you using dask-kubernetes or the dask helm chart?

**Comment by pintuiitbhi** [comment]
For learning purpose, First I tried using helm. It works. I got a jupterhub and from there I can work.

For adaptive clustering I just opened a notebook in my localhost and run the following code from the quick start of documentation
[code](https://kubernetes.dask.org/en/latest/#quickstart)

**What should I do so that my code run on kubernetes cluster on AKS not locally?** Locally I have to create worker from terminal "dask-worker <scheduler ip> " then only works.

**Comment by TomAugspurger** [comment]
I don't think any of the dask-kubernetes maintainers have used AKS extensively. The jupyterhub devs have a good guide for these: https://zero-to-jupyterhub.readthedocs.io/en/latest/create-k8s-cluster.html. You may need to configure your shell to point to that cluster.

I'm closing this, since it doesn't appear to be directly related to dask-kubernetes. I'm sure
future readers would appreciate if you're able to provide details on what worked, and we can
maybe turn that into improved docs.
