### ISSUE TITLE
Asynchronous processing

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-kubernetes#16]
I notice that the kubernetes API has an `async=` keyword.  Do you happen to know if people use this library with Tornado?

Incidentally this library is new and pops up in web searches: https://github.com/kippandrew/client-python-tornado  It's obviously very new though.

**Comment by mrocklin** [comment]
Or maybe swagger can give this to us magically?

**Comment by mrocklin** [comment]
@yuvipanda if I reall correctly you mentioned that there was an asyncio kubernetes library that was decent.  Would you mind pointing out which one you meant here?  (doing a web search turns up a couple)

**Comment by mrocklin** [comment]
Never mind, on further investigation I see that @yuvipanda has been committing to https://github.com/olitheolix/aiokubernetes

**Comment by yuvipanda** [comment]
@mrocklin https://github.com/kubernetes-client/python/issues/323 has discussion and links to two libraries. The one you linked to, and https://github.com/tomplus/kubernetes_asyncio. It's unclear which one to throw weight behind :) I like the design of https://github.com/olitheolix/aiokubernetes better though.

the async= parameter in kubernetes API is pretty bad - it makes a new thread and returns it! I think it has been changed to making a new threadpool and returning a thread from it, but I wouldn't consider any of these good python practices.

@minrk also has thoughts on this.

**Comment by minrk** [comment]
The ThreadPool approach in kubernetes >=4 is the same as the one we use in kubespawner/binderhub (return ThreadPoolExecutor.submit(blocking_func)`), and it works great (we just run kubernetes calls in a background thread of our own instead of passing an async arg per call). The downsides of using Python threads are often overstated, but a native asyncio API is still nice. From the looks of the examples, I would pick `kubernetes_asyncio`, which seems to have the most "the same as before, but add `await`" API, rather than what appears to be a much more complex and verbose API in aiokubernetes.

**Comment by jacobtomlinson** [comment]
Closed in #162

**Comment by mrocklin** [comment]
Woo!
