### ISSUE TITLE
JupyterLab extension

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-kubernetes#23]
It would be useful to have a JupyterLab extension to launch Daskernetes clusters.

**Comment by yuvipanda** [comment]
A good start would be:

1. When the notebook process starts, start a dask-scheduler process on a well known port. This can be connected to easily from various notebooks, and nbserverproxy has code for supervising this process.
2. Register a route for dask dashboard so users can access it at /dask-dashboard
3. Write some UI to make these URLs visible in the interface

**Comment by mrocklin** [comment]
So for UI we probably want options to scale the cluster, put it into adaptive mode, etc..

Thinking about this a bit more though, we could also put this on the dask dashboard itself.  Historically the scheduler dashboard has always been about publishing diagnostics, there is no reason why we couldn't add a page to do some control as well though.  This would remove most of the burden of writing a JLab extension.  Presumably we would just want a button to launch the dashboard, which in this case is just a link to `/dask-dashboard` from somewhere in the interface.

**Comment by mrocklin** [comment]
Ah, we already have an issue here.  My current guess at an ideal user perspective is as follows:

- The notebook extension would provide a few user inputs:
    - Enough UI to define a worker pod spec, this might just be a path to a worker spec yaml file, or it might be a bunch of options for memory, cpu use, image, etc.. (I would just do the yaml file to start if it was me and offload configuration to a text editor).
    - An option to start a KubeCluster with these options
    - The ability to scale the KubeCluster and see the current number of workers, as is currently done in the ipython widget
    - An option to stop the cluster (presumably the same as the start/launch button?)

It's not clear to me when it should start a dask scheduler.  In practice I can imagine this being installed on a common user environment that was rarely used for Dask, so it might be better to only launch the scheduler when the user actually selects a worker pod spec and presses some sort of "launch" button.

**Comment by mrocklin** [comment]
@yuvipanda it may also be that I'm conflating notebook extension with JLab extension.  I may not fully understand your thoughts here.

**Comment by yuvipanda** [comment]
There are two things here:

1. A Notebook Server extension, to provide access to the dask dashboard. This might or might not have any UI at all, but is what allows users to access dashboard at something like `/user/<username>/proxy/<port>`. In pretty much most kubernetes clusters, if you are using Jupyter Notebooks (standalone or as part of JupyterHub), you need this - you do not want to expose your dashboard to the internet directly (for security reasons), and you might not be able to (because it is running in same pod as your notebook, or you do not have enough public IPs, etc). This is common to both classic notebook and lab.

2. A JupyterLab client, which *purely* does client UI modifications. This can also have a serverside component if we wish, but is just arbitrary javascript that can do arbitrary JS things, including talk to various servers / talk to the currently running Kernel (I think). This is super optional, and just provides nice UI for doing things that might otherwise require code.

My hope is we can bundle both of these into one python package, and allow knobs to turn the UI off if people do not like it. But we can start off by just implementing (1).

Does that make it a bit more clear?

**Comment by mrocklin** [comment]
Separating those two like that does help, yes.  My understanding is that part 1 is already done with `nbserverproxy`.  Is there any work there that remains?

Historically you've mentioned having this extension also start up a dask scheduler process in the background.  I think that this will be a bit tricky because I think that our KubeCluster logic will want to be in the same process as that scheduler, so we're going to want to poke it from time to time to give it inputs.  I don't know how to make progress on this front without having some UI elements.

**Comment by yuvipanda** [comment]
The only work that remains for (1) is letting the user know which URL to use, which depends on the port the dashboard is running on, which can be dynamically determined. It also needs to be printed only if nbserverproxy is installed. Other than that, yes I think that is done.

I am unsure if the dask scheduler-in-background is the right thing to do or not. I don't have a good intuition for it, since I'm unsure how people using it in practice want it to behave. Having more user stories here would help I am sure.

**Comment by mrocklin** [comment]
> The only work that remains for (1) is letting the user know which URL to use, which depends on the port the dashboard is running on, which can be dynamically determined. It also needs to be printed only if nbserverproxy is installed. Other than that, yes I think that is done.

This seems like it would be a very minor change on top of the vanilla `nbserverproxy` extension.  One that also provided an environment variable with a format string or something.  If that's the case then it seems like we might be able to get by with the vanilla `nbserverproxy` extension and be done with it.  I'm slightly afraid of having our special `nbserverproxy` extension go stale in the future for lack of maintenance.

**Comment by jacobtomlinson** [comment]
This exists now over in the Dask Jupyter Lab extension. See the [kubernetes section of the docs](https://github.com/dask/dask-labextension#configuration-of-dask-cluster-management).
