### ISSUE TITLE
Kubernetes Operator

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-kubernetes#256]
Should we maintain a Kubernetes Operator?

There are a few Kubernetes projects out there (dask-kubernetes, dask-helm, dask-gateway, various internal company projects).  They exist because they all have slightly different needs and serve different use cases.  This makes sense.  In the end it's not terribly difficult to make a new Kubernetes + Dask thing.  However, I'm curious if there are lower level structures that we could build that could be shared among a few of these.

(disclaimer: I suspect that I'll be in this situation again , and so am looking around)

One reason why we keep doing our own logic, rather than using internal k8s controllers is that our scale-up/scale-down logic is more complex than most.  As a result we tend to manage pods directly.  I wonder if putting this logic into an operator might allow more code reuse among projects.  

I don't know this space well though, and it may be that Operators bring in their own baggage that we want to avoid.

As maybe a pragmatic question.  If we had an operator what would dask-kubernetes and dask-helm look like on top of that system?  My guess is that ...

-  For dask-kubernetes we would move a lot of the scaling logic in dask-kubernetes to dask-kubernetes-operator (or some better name) and mostly change this library to just modify values in a custom resource.  We would have to launch one additional pod (one operator per cluster?)
-  For dask-helm we would gain the ability to scale down smoothly I think

**Comment by jacobtomlinson** [comment]
I've been considering the same thing recently. There are positives and negatives to using operators, but I think the scaling logic may make a good case for doing this.

I'd be keen to hear what @yuvipanda thinks.

**Comment by jcrist** [comment]
dask-gateway contains an operator, but its highly tailored to dask-gateway's internals. In my experience, operators as you probably mean them are for the following use case:

- You have a custom resource definition (CRD) for describing your objects. In this case you'd probably have a `DaskCluster` object that would store specs for a dask cluster.
- You want to interact with that object using the k8s api (e.g. use `kubectl` to scale that object).

Dask-Gateway is a weird use case, where we're using k8s objects instead of a database to store state, but we don't want users to interact with dask clusters via the k8s api.

I think an operator for dask could be nice, but they also add complications - you need a new service running on k8s, with SA permissions, it's one-more-thing to watch. I personally don't see a use case in the ecosystem for one at this point.

**Comment by jacobtomlinson** [comment]
Those are good points @jcrist.

I see value in having a CRD with operator handle the scaling in a bespoke way for Dask. It would almost be like a custom HPA which asks the scheduler for information on what pod to remove.

I would also like to have the option of `kubectl scale daskcluster/<cluster name> --replicas=5` as it would feel normal to regular Kubernetes users. If we do this currently with the `Deployment` resource (like the one in the Helm Chart) scaling down can result in lost futures.

I'm curious to know more about why you chose CRDs to store state instead of serialising into a config map. Were there benefits to this approach?

I also think that trying to put some common code into dask-kubernetes, the helm chart and dask-gateway would be useful for reducing maintenance burden over all. But we've discussed that before.

**Comment by jacobtomlinson** [comment]
But I also agree that CRDs and operators can add unpleasant complexity for naive uses of Kubernetes. I set up [Cert Manager](https://github.com/jetstack/cert-manager) recently on a cluster, which is an extremely great and powerful tool, but for my simple use case I really just wanted [kube-lego](https://github.com/jetstack/kube-lego) back.

**Comment by DavidSpek** [comment]
The past months I've been working with Kubeflow and I think it might be interesting to integrate Dask into Kubeflow. Kubeflow [provides](https://www.kubeflow.org/docs/reference/) operators and CRDs for launching TFJob, PyTorchJob and Notebooks for example. I've tried running dask-kubernetes in a notebook server on Kubeflow but I am running into the error `AttributeError: 'V1Pod' object has no attribute 'openapi_types'`, which is why went looking for an operator. 

Are you aware that an operator for dask already exists (technically 2 but this one is more recent)? https://github.com/piersharding/dask-operator

**Comment by jacobtomlinson** [comment]
Thanks for highlighting that project! I was not aware of it.

**Comment by DavidSpek** [comment]
I think it might be interesting to reuse the Kubeflow Notebook operator to launch notebooks to reduce duplication of code (and potentially easy integration with Kubeflow). https://github.com/kubeflow/kubeflow/tree/master/components/notebook-controller

**Comment by jacobtomlinson** [comment]
While I agree in principal there is reasonably limited Golang experience within the Dask community. We have endeavoured in the past to remove Golang from other places (dask-gateway) in favour of Python, from a maintainability point of view.

**Comment by DavidSpek** [comment]
While I have basically no experience with Golang and I completely understand wanting to use Python for maintainability, I'd like to note that the operator is built using Kubebuilder. While I also have no experience with Kubebuilder, it is my understanding that it greatly simplifies the creation of operators by having standard templates for things such as creating a webhook. 
https://github.com/kubernetes-sigs/kubebuilder

**Comment by yuhuishi-convect** [comment]
Hello, I am not sure if this issue is still relevant. 
I would like to bring up the attention to our recent work [dask-operator](https://github.com/yuhuishi-convect/dask-helm-operator). This is based on [operator-sdk](https://sdk.operatorframework.io/) to wrap around dask helm charts to manage clusters on k8s. 

The project is used within my company [Convect.ai](https://convect.ai) to provide on-demand clusters (together with k8s api) for computation tasks. The repo needs some help to set up things like documentation, syncing with dask helm charts, continuous releasing. Would be great if we can get some advice from the community.

Our team has many experiences working with Go and projects like kubeflow. And we are glad if we could help in those directions as well.

**Comment by jacobtomlinson** [comment]
Thanks so much for sharing @yuhuishi-convect that's really interesting. We are about to spin up a new project next week to finally build a Kubernetes operator for Dask so we will definitely take a look at what you've built.

One of the main things we want to achieve is better support for autoscaling and adaptive clusters. The Dask helm chart doesn't really support this very well. Dask Kubernetes does support this but isn't really an ideal approach anymore and an operator would be preferable.

Looking at your code I'm curious if you've explored [Dask Gateway](https://gateway.dask.org/). It seems ideal for your use case.

**Comment by yuhuishi-convect** [comment]
@jacobtomlinson 

Supporting adaptive cluster sounds very interesting.
I know that in Ray project, they have a dedicated service that handles the scaling up/down decisions (and calls k8s api to trigger those actions) as part of a cluster deployment, while the CRD operator only handles creation/deletion of native k8s resources.

Will stay tuned.

**Comment by jacobtomlinson** [comment]
Yeah the idea is to create a new CRD operator for a Dask cluster which will behave similarly to a Deployment coupled with an HPA. So it will create pods automatically for workers and scale up and down with demand. But when adding/removing it will communicate with the Dask scheduler to intelligently manage those resources without losing state.

**Comment by stephan-erb-by** [comment]
Hey everyone,

it is great to see some recent momentum on the official Dask operator!

We have implemented an in-house Dask operator and are open to share our experiences with the community. We are aware that it might not fully match the direction of the project, but maybe you can benefit from some of our learnings.

What we have:
- A Kubernetes custom resource (CRD) for Dask distributed. The CRD is namespace scoped. On a typical Kubernetes cluster we have dozens of Dask instances running spread across multiple namespaces. 
- Operator implementation for the CRD using Python 3.9 and Kopf
- The operator is independent of the Dask distributed version of a particular scheduler/worker. The operator has to communicate with the scheduler, but to be independent of a Dask version we have introduced a customer scheduler plugin so that we can communicate via HTTP. We secure this communication using network policies.
- The operator creates required Kubernetes resources to start a Dask scheduler and its workers on Kubernetes, this includes:
   - Custom scheduling priorities to support dev and production workloads on the same cluster
   - Custom env vars
   - Support for additional volumes and files
   - Secret injection from Azure Key Vaults
   - Injection of Azure managed identity credentials
- Dask workers are modeled as individual Kubernetes deployments (i.e., one deployment for each worker) so that they can be shutdown separately. This gives us great control for graceful termination (see below).
- We are using Istio as our service mesh. Istio is also used to secure the scheduler/worker communication (instead of using the TLS support of Dask). As a workaround for https://github.com/dask/dask-kubernetes/issues/197 we give each worker its own service. 
- Graceful shutdown of Dask workers implemented via custom scheduler routes. If there is a need to scale down, we query the scheduler for the least important workers to be terminated. During shutdown workers still receive incoming connections from other workers to transfer their data. To workaround the Kubernetes behaviour that terminating PODs can no longer receive new incoming connections, we take special care of a proper shutdown sequence. 
- There is an open challenge with how readiness probes in Kubernetes interact with Dask. A worker assumes it is immediately callable once it could reach the scheduler. Given how services work in Kubernetes this is not always the case. We have a workaround in place, but still need to come up with a longterm solution.

We are using what we outlined above together with a custom autoscaler. The autoscaling is aware of the total Kubernetes cluster resources. If multiple Dask cluster are competing for resources, then the operator uses the Dominant Resource Fairness algorithm to decide how many resources are assigned to each. This enables multiple teams to simultaneously use a single Kubernetes cluster and max out all available resources. This might be harder to extract as it contains more proprietary domain knowledge. The auto-scaling is based on the `desired_workers` metrics exposed by the scheduler.

If you are interested, we are happy to jump on a call with you to explain what we have discuss this further. We still need to figure out if/how we can extract our code, but this should not block any discussion. 
 
Please let us know if you are interested.

**Comment by jacobtomlinson** [comment]
Thanks for reaching out @stephan-erb-by, sorry for the delay in responding, that sounds really exciting. It seems we are on the road to building something very similar to what you have already done over in #392. With the goal being to release a BSD licensed operator as part of the `dask-kubernetes` package.

I really appreciate the offer of sharing your knowledge, from reading your description I have a bunch of questions! Having a call would be great, we should make sure things are communicated back to the community as best as possible too.

Feel free to drop something into my [calendar](https://jacobtomlinson.dev/calendar), I'll forward the invite to @matt711 who is also working on #392 and we can take notes and report back here after.

**Comment by Matt711** [comment]
Notes meeting with Stephan and Phillipp:
- We want the Dask Operator to be independent of the Dask distributed version of a particular scheduler or worker. Therefore, we are thinking about possibly implementing a REST API via plugin for Dask Distributed instead of connecting to the scheduler via rpc. Bidirectional connectivity (let the scheduler ping the worker to see if it's ready or not) [#5934](https://github.com/dask/distributed/issues/5934)
- We talked about possibly adding a Kubernetes deployment resource in addition to the worker group resource so that we're not creating the worker pods directly. And this might provide a better way of terminating the workers.
- Support for using Istio, maybe giving each worker their service?

**Comment by jacobtomlinson** [comment]
We just released `2022.4.0` which contains an experimental version of the new operator. We are keen for folks to try it out and give us feedback. Check out the [docs here](https://kubernetes.dask.org/en/latest/operator.html).

**Comment by yuhuishi-convect** [comment]
> We just released `2022.4.0` which contains an experimental version of the new operator. We are keen for folks to try it out and give us feedback. Check out the [docs here](https://kubernetes.dask.org/en/latest/operator.html).

Awesome, is it hosted under the main dask repo?

**Comment by Matt711** [comment]
The operator exists [here](https://github.com/dask/dask-kubernetes/tree/main/dask_kubernetes/operator). The cluster manager for the operator (`KubeCluster`) is [here](https://github.com/dask/dask-kubernetes/blob/main/dask_kubernetes/experimental/kubecluster.py)

**Comment by jacobtomlinson** [comment]
Now that the operator exists and we are actively developing it I've broken the remaining tasks out into issues and created a few milestones to track things. I think we can safely close this issue as everything from here and the original operator feature branch have been captured in those issues.

Milestones:
- [Support Kubeflow](https://github.com/dask/dask-kubernetes/milestone/2)
- [Feature parity with classic `KubeCluster`](https://github.com/dask/dask-kubernetes/milestone/1)
- [Feature complete (everything we aspired to in this issue)](https://github.com/dask/dask-kubernetes/milestone/3)
