### ISSUE TITLE
Maintain minimum number of workers alive

### ISSUE THREAD

**Issue by BitTheByte** [dask/dask-kubernetes#417]
**What happened**:
When using `KubeCluster` if one or more worker pods die or error out `dask-kubernetes` totally ignores it both when using `n_workers` or `adapt_kwargs={"minimum": min_workers, "maximum": max_workers}`

**What you expected to happen**:
I expect worker pods to restart or at least maintain their minimum number 

**Environment**:

- Dask version: `2022.1.0`
- Python version: `3.9`
- Operating System: `Ubuntu 20.01`
- Install method (conda, pip, source): `pip`

**Comment by jacobtomlinson** [comment]
Thanks for raising this. I think this is mostly expected behaviour with manual scaling and I am unable to reproduce the issue in adaptive mode. I note that you are not using the common syntax for adaptive, perhaps this is where the problem lies.

When calling `cluster.scale(n)` this action will scale to that number of workers, but will make no attempt to keep it at this number if some external factor changes it. For example:

* Create a cluster using the minimal example from the docs.

```python
from dask_kubernetes import KubeCluster, make_pod_spec

pod_spec = make_pod_spec(image='daskdev/dask:latest')
cluster = KubeCluster(pod_spec)
cluster.scale(10)
```

* Wait for all 11 pods to start (scheduler plus 10 workers)
* Choose a worker pod and list its processes.

```console
$ kubectl exec dask-jtomlinson-2838bbf8-95fx7p -- ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   2504   576 ?        Ss   09:13   0:00 tini -g -- /usr/bin/prepare.sh dask-worker tcp://dask-jtomlinson-2838bbf8-9.default:8786 --nthreads 1 --death-timeout 60 --name 9
root          12  5.0  0.7 797580 59880 ?        Sl   09:13   0:06 /opt/conda/bin/python3.8 /opt/conda/bin/dask-worker tcp://dask-jtomlinson-2838bbf8-9.default:8786 --nthreads 1 --death-timeout 60 --name 9
root          19  0.0  0.1  13088 10920 ?        S    09:13   0:00 /opt/conda/bin/python3.8 -c from multiprocessing.resource_tracker import main;main(11)
root          21  7.9  1.4 958784 116796 ?       Sl   09:13   0:10 /opt/conda/bin/python3.8 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=12, pipe_handle=18) --multiprocessing-fork
root          40  0.0  0.0   7656  3272 ?        Rs   09:15   0:00 ps aux
```

* Kill the Dask Worker process manually (in this case PID 12)

```console
$ kubectl exec dask-jtomlinson-2838bbf8-95fx7p -- kill -9 12

```

* The pod will go into error state and then be removed
* Note that the cluster now has 9 workers and does not automatically scale back to 10.

This is why the adaptive mode exists, it will automatically scale based on configuration and work submitted. If you want to always retain 10 workers you can do `cluster.adapt(minimum=10, maximum=n)`.

* Create a cluster using the minimal example from the docs.

```python
from dask_kubernetes import KubeCluster, make_pod_spec

pod_spec = make_pod_spec(image='daskdev/dask:latest')
cluster = KubeCluster(pod_spec)
cluster.adapt(minimum=10, maximum=20)
```

* Wait for all 11 pods to start (scheduler plus 10 workers)
* Choose a worker pod and list its processes.

```console
$ kubectl exec dask-jtomlinson-2838bbf8-95fx7p -- ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   2504   576 ?        Ss   09:13   0:00 tini -g -- /usr/bin/prepare.sh dask-worker tcp://dask-jtomlinson-2838bbf8-9.default:8786 --nthreads 1 --death-timeout 60 --name 9
root          12  5.0  0.7 797580 59880 ?        Sl   09:13   0:06 /opt/conda/bin/python3.8 /opt/conda/bin/dask-worker tcp://dask-jtomlinson-2838bbf8-9.default:8786 --nthreads 1 --death-timeout 60 --name 9
root          19  0.0  0.1  13088 10920 ?        S    09:13   0:00 /opt/conda/bin/python3.8 -c from multiprocessing.resource_tracker import main;main(11)
root          21  7.9  1.4 958784 116796 ?       Sl   09:13   0:10 /opt/conda/bin/python3.8 -c from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=12, pipe_handle=18) --multiprocessing-fork
root          40  0.0  0.0   7656  3272 ?        Rs   09:15   0:00 ps aux
```

* Kill the Dask Worker process manually (in this case PID 12)

```console
$ kubectl exec dask-jtomlinson-2838bbf8-95fx7p -- kill -9 12

```

* The pod will go into error state and then be removed
* A few seconds later a new pod is spawned to replace the errored pod.

**Comment by BitTheByte** [comment]
Hi @jacobtomlinson 

Apologies, the seems to be unrelated to `dask_kubernetes` itself. Yes you're right I tested this using [PrefectHQ/prefect](https://github.com/PrefectHQ/prefect) `DaskKubernetesExecutor` which under the hood uses this library I filled an issue on there side https://github.com/PrefectHQ/prefect/issues/5549

 Thank you! :)
