### ISSUE TITLE
Fix chartpress release of dask-kubernetes-operator

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-kubernetes#491]
It looks like chartpress isn't setting the Docke image tag correctly and the chart is not installable.

https://github.com/dask/dask-kubernetes/blob/bf1b6a480713cb7dce397574047c9adf99e72a37/.github/workflows/release.yml#L65-L74

_Originally raised in https://github.com/dask/helm-chart/pull/266#issuecomment-1125362071_

**Comment by jacobtomlinson** [comment]
@consideRatio could you point me in the right direction to get chartpress to update the Docker image tag in `values.yaml`?

Chartpress currently doesn't handle the build and push of the Docker image because the image is used for more than just the helm chart. We build and push that with the Docker GitHub Action before publishing the helm chart. Is that what is causing the issue?

https://github.com/dask/dask-kubernetes/blob/bf1b6a480713cb7dce397574047c9adf99e72a37/.github/workflows/release.yml#L56-L63

**Comment by consideRatio** [comment]
The reason the Helm chart currently doesn't get image versions etc updated by any call to `chartpress` the CLI is because the `chartpress.yaml` configuration doesn't mentions any images. The `dask-gateway` helm chart [does so here](https://github.com/dask/dask-gateway/blob/01eef766f05d3ff91718b134ccb9490b02f50671/resources/helm/chartpress.yaml#L23-L41).

Note that the `ghcr.io/dask-gateway-server` image could in theory also be used by something else than the Helm chart, it is also used by the Helm chart so the Helm chart should always be updated as well.

Note that:
- if the image should be re-built, the helm chart should be re-packaged.
- if the helm chart is changed without changes to the image, the helm chart should be re-packaged but re-use the existing build of the image.

I'd say there is a coupling to the Helm chart, but a user of the image doesn't have to be aware of the Helm chart. I see two options. One is to let chartpress manage the build and tagging of the image, or add automation like [done in z2jh for images not maintained in the z2jh project but used by the Helm chart](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/.github/workflows/watch-dependencies.yaml#L23). My suggestion based on experience is to rely on chartpress for anything maintained in the same project.

**Comment by jacobtomlinson** [comment]
Thank you that's super helpful. I've raised #492 if you don't mind having a look?
