### ISSUE TITLE
Remove password from default jupyter configuration

### ISSUE THREAD

**Issue by ckemere** [dask/dask-kubernetes#54]
Last week, I found dask-kubernetes and was excited to play around with it. It ended up taking me a couple of days of work to get the docker container re-compiled so that I could test it. This is because the password for the jupyter notebook is not specified. Why not disable the password by default?

**Comment by martindurant** [comment]
Jupyter strongly suggests that all servers open to the world should be at the very least password protected.  Since the appearance of the URL token for the notebook server, I'm not sure if it would even accept connections from not-localhost without password or token.
The default is right in the README, and there are instructions for how to generate a new one.

**Comment by ckemere** [comment]
Embarrassing - I somehow skimmed right over the password multiple times. Sorry about that!
