### ISSUE TITLE
Use of "pods" vs "workers"

### ISSUE THREAD

**Issue by jacobtomlinson** [dask/dask-kubernetes#56]
I have found that people using our system have no concept of what kubernetes is, and frankly there isn't really a requirement for them to know the details other than it is a kind of scheduler.

But then I get questions like "How do I get the worker logs" and my answer includes a call to `cluster.pods()`. At which point I have to explain what a pod is and its relationship to a worker.

I would find it useful to remove the kubernetes specific language for end users. It would make more sense for them to call `cluster.workers()`.

I would be keen to hear others thoughts on the matter.

**Comment by mrocklin** [comment]
I think that there is value to both user-facing and developer-facing method
names.

I wonder if this can be resolved by changing the logs method (which
presumably has an intuitive name) rather than the pods method.  What API do
you think would be the most intuitive for users?  For example we could have
logs() with no arguments return a dictionary mapping address to log
results.  This would avoid the extra and confusing call to pods.

**Comment by jacobtomlinson** [comment]
Yes changing `logs()` would be better. 

I like the idea of calling logs with no arguments.

**Comment by jacobtomlinson** [comment]
This is out of date now.
