### ISSUE TITLE
Ability to configure port for forwarding

### ISSUE THREAD

**Issue by patmagauran** [dask/dask-kubernetes#615]
Right now, the cluster scheduler's dashboard port is forwarded to a random system port. Ideally this port should be configurable for deployments where that makes sense. For example, I am running this in docker on windows and thus can't use host networking for the docker container and obviously can't forward every possible port from the container. 

I am willing to make the changes necessary, but I just wanted to see any feedback prior to submitting a PR.

**Comment by jacobtomlinson** [comment]
Could you share how you are creating your cluster, this project has a few different tools in and it's unclear which you are referring to?

**Comment by jacobtomlinson** [comment]
Ok great I understand. Yeah making the port-forward local port configurable makes total sense. I also wonder if by default we should try and forward to the default ports (8786 for the comm and 8787 for the dashboard) and fall back to random ports if those are in use.

Dask has a config system which supports env vars and more, so that would be the preferred way to implement this.

**Comment by patmagauran** [comment]
I will look into adapting my current work into the dask config setup and submit a PR shortly.
