### ISSUE TITLE
Unable to retrieve pod logs 

### ISSUE THREAD

**Issue by jgerardsimcock** [dask/dask-kubernetes#64]
I am trying to understand the relationship between the workers and pods. To this end, I have tried a few methods and have been unsuccessful. 

The first method using kubectl: 
<img width="599" alt="screen shot 2018-04-05 at 7 42 03 am" src="https://user-images.githubusercontent.com/6101444/38382194-e89c3326-38a4-11e8-9dc8-0f8c81a3e6ae.png">

?...This is confusing. 

The second method using dask_kubernetes `cluster.log(pod)` raises what looks like an rbac error.
Here is the output from `cluster.log(cluster.pods()[0])`:

<img width="950" alt="screen shot 2018-04-05 at 7 47 55 am" src="https://user-images.githubusercontent.com/6101444/38382654-2c636dbc-38a6-11e8-9c26-71c72758cf80.png">

Its not clear to me where to modify rbac privileges so the single-user notebook can have access to the worker logs.

**Comment by jacobtomlinson** [comment]
This is something I am actively looking at. 

Could you provide more information about how you deployed your cluster?

**Comment by jgerardsimcock** [comment]
I followed your instructions [here]( https://github.com/informatics-lab/jade-pangeo ). [Here](https://github.com/RhodiumGroup/rhodium-pangeo) is our helm deployment. The docker images this is based on our essentially the same as those in the pangeo image but I've removed the example dir with the jupyter notebooks.

**Comment by jacobtomlinson** [comment]
Thanks for the info.

We have since updated our repo to use the [official pangeo helm chart](https://github.com/pangeo-data/helm-chart). This means the RBAC stuff can be managed upstream.

I still ahven't got it configured quite right. The issue is down to the [Role](https://github.com/RhodiumGroup/rhodium-pangeo/blob/master/rhg-pangeo/templates/dask-kubernetes-rbac.yaml#L15) not having the right permissions to read the logs. 

I'm currently adding it to the official chart, but for now you may want to update [this line](https://github.com/RhodiumGroup/rhodium-pangeo/blob/master/rhg-pangeo/templates/dask-kubernetes-rbac.yaml#L27) to be `resources: ["pods", "pods/log"]`

**Comment by jgerardsimcock** [comment]
Thank you @jacobtomlinson. Will update that file and push.

**Comment by jacobtomlinson** [comment]
I've actually updated it to look like [this](https://github.com/pangeo-data/helm-chart/pull/8/files).

Because we only need list and get perms for logs.

**Comment by jacobtomlinson** [comment]
@jgerardsimcock I take it by closing the issue that worked for you?
