### ISSUE TITLE
Add batched worker provisioning to Dask Cluster spawning on Kubernetes

### ISSUE THREAD

**Issue by akangst** [dask/dask-kubernetes#733]
In Spark on Kubernetes, there is an option to set a batch size for the number of workers that are spun up simultaneously within a larger job. An example of this would be with 100 workers and batch size of 10, the distributed scheduler will spin up 10 gangs of 10 workers each sequentially to lessen load on the kubernetes scheduler as it provisions each gang. There is also an option to set a time delay, so instead of waiting for each batch to complete, instead it waits for n seconds to make the next request. 

It would be nice if Dask could implement similar functionality for batched worker provisioning. We find that in our use case, we start to have problems with the IAM provider in AWS above 40 simultaneous worker requests, and especially in large clusters of 100 or more. We have worked around it by adding sleeps or exponential backoffs to the container images in use, but if it could be adjusted at the cluster level, it would smooth out large cluster provisioning without needing kludges. 

Thanks - DH

**Comment by jacobtomlinson** [comment]
I'm surprised you're seeing this problem with such a small number of workers, I'd like to know what IAM plugin you're using and whether any improvements could also be made there.

This is a useful feature for us to implement though. 

We should make a small modification to the scale-up code to add a max to the number of workers that it adds along with a cooldown before continuing.

https://github.com/dask/dask-kubernetes/blob/bebb5d16ded76a70755429e61f8004eaa5e9e7d2/dask_kubernetes/operator/controller/controller.py#L621-L637

I feel like setting this batch size and cooldown would make sense to configure on the operator, rather than on a cluster-by-cluster basis. Interested to hear if you agree.

To do this we would need to add a new config option to the Operator Helm Chart values.yaml

https://github.com/dask/dask-kubernetes/blob/bebb5d16ded76a70755429e61f8004eaa5e9e7d2/dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/values.yaml

Then pass that through to the controller via a CLI argument or env var (would need to check the kopf docs to see which makes the most sense).

https://github.com/dask/dask-kubernetes/blob/bebb5d16ded76a70755429e61f8004eaa5e9e7d2/dask_kubernetes/operator/deployment/helm/dask-kubernetes-operator/templates/deployment.yaml#L29-L45

Then capture that option on startup for use in the scaling handler

https://github.com/dask/dask-kubernetes/blob/bebb5d16ded76a70755429e61f8004eaa5e9e7d2/dask_kubernetes/operator/controller/controller.py#L219-L220

**Comment by akangst** [comment]
So, I think it makes sense in the operator - but I also think it makes sense on a basic cluster more, because then you cover the plain dask-on-k8s use case, and with that it allows for adding to the config for dask gateway as well, since that uses kubeCluster under the hood for its optional config. We're running flavors of all 3 in places, and it seems like you would have to do it twice with the operator and kubeCluster - though maybe it's worth doing in both. 

In general, we're still stuck on the KIAM IAM provider, and it's largely abandonware, but past architectural decisions are preventing a clean migration to IRSA right now, so it's what I'm stuck with. This is sort of an odd problem, in that if the users spin up ~50 workers, and there's enough pre-existing capacity on a cluster so they spin up without having to scale up new nodes, it happens since we rate limit the IAM system, but if the workers are large or scaling needs to happen with a lot of pending workers, then I don't run into the same issues. Either way, a way to gang or batch schedule groups of workers is going to smooth out provisioning. 

We have large clusters too, usually we use an exponential backoff check against aws sts in the container entrypoint for those. That's really not my favorite design.

**Comment by bstadlbauer** [comment]
I think we might be running into the same issue on GKE when a lot of `dask` clusters are coming up at the same time, but haven't seen this too often to warrant a deep dive. Happy to look into things though in case it helps

**Comment by jacobtomlinson** [comment]
It sounds like you're referring to the classic KubeCluster, the modern operator-based KubeCluster, and Dask Gateway. Each are distinct projects and need to be handled separately. The classic implementation is going away so we don't need to worry about that. If this feature is also desirable in Dask Gateway I recommend opening a similar issue on that project too.

**Comment by akangst** [comment]
Yeah, those are the three flavors of dask on k8s. I wish everything I had was the operator right now. :)

I think even though dask gateway is a bit of a bastard child, you can override it with the kubecluster settings for defaults on the spawned clusters. An example code snippet is here. I think any fixes in kubeCluster classic can be rolled into that without explicitly putting it in. I could be wrong, but thats what it feels like working on it. 

I'll take the advice on opening an issue there too, but explaining why I made the previous statement. I'm familiar enough with gateway it might be worth making the enhancement PR myself if they're open to it. 

`# Configure the dask cluster image
    image_name = get_property("gateway.backend.image.name")
    if image_name:
        image_tag = get_property("gateway.backend.image.tag")
        c.KubeClusterConfig.image = (
            "%s:%s" % (image_name, image_tag) if image_tag else image_name
        )
        c.KubeClusterConfig.image_pull_secrets = get_property("gateway.backend.imagePullSecrets")`

**Comment by jacobtomlinson** [comment]
> I wish everything I had was the operator right now. :)

🎉

> you can override it with the kubecluster settings for defaults on the spawned clusters

Gateway and KubeCluster classic are totally separate codebases with no relation, so I'm not sure what you mean.
