### ISSUE TITLE
Add IngressSpec besides ServiceSpec to Scheduler

### ISSUE THREAD

**Issue by jonded94** [dask/dask-kubernetes#892]
Hi!

We're extensively using `DaskCluster`'s right now and really benefit from the great Dashboard that the scheduler provides. 

To make the HTTP Dashboard accessible from our companies' VPN, we have an additional step on every creation of a Dask cluster where we also create an k8s `Ingress` pointing to the scheduler's service. This is a bit cumbersome, not only because you have to create the ingress, but also make sure that you delete it properly afterwards. If something goes wrong here, you could end up with dead, unused ingresses.

The scheduler already provides a place to define the Service [here](https://github.com/dask/dask-kubernetes/blob/77b90433872938003bb42e20133aa6c09c66c185/dask_kubernetes/operator/customresources/templates.yaml#L50). Could we also define a `Ingress` here? What do you think?

**Comment by jacobtomlinson** [comment]
Thanks for raising this @jonded94, glad you're enjoying Dask.

I'm pretty cautious about adding new nested resources to the spec because it could easily snowball as people request more and more things to be added. I would prefer people to create additional resources independently, but I'm very open to improving tooling to make that easier.

We set [owner references](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/) on all the child resources we create so that when the `DaskCluster` resource is deleted they get automatically cleaned up by Kubernetes. You could make the `Ingress` a child of the `Service` so that it gets cleaned up automatically.

```python
# Here's an example in Python, you could equally do this with kubectl
from kr8s.objects import Service, Ingress

# Create your Ingress
ingress = Ingress({...})  # Your Ingress spec goes here
ingress.create()

# Make the Ingress a child of the Service
service = Service.get("your-cluster-service-name")
service.adopt(ingress)  # Now when the service gets deleted the Ingress will be deleted automatically
```

**Comment by jonded94** [comment]
Tried that out, works great! Thanks a lot :)
